### ISSUE TITLE
Button to open FileManager

### ISSUE THREAD

**Issue by SGiuseppe** [jc3213/download_with_aria2#5]
Premise, I like the project but it would be useful a button that opens me on the filemanager the downloaded file location

**Comment by jc3213** [comment]
There's no API I could find to open the download folder. If there's any available API, I've added this function long time ago.

**Comment by g-eipi10** [comment]
I think extensions are not allowed to open local folders. In that case, it would be nice to have a copy button so user can copy the folder path and open it via another shortcut key software like Autohotkey, or can just simply paste that folder path to the file explorer to open it quickly.

**Comment by SGiuseppe** [comment]
I installed DownThemall and Download Manager (S3) using the right button on the downloaded files there are two "Open File" and "Open Folder" entries. I don't know if as an example it can be useful

**Comment by jc3213** [comment]
I've looked into `Download Manager (S3)`'s source code, and also tried it.

It's a manager that manages browser's download, not a third-party download program's web interface. Plus, it can use `chrome.downloads.show(downloadId)`  to open the folder that contains the download. This is restrict to use native `downloads` API to manage the downloads. Downloads captured by extension are removed from history. Eevent if not, you can't get the download id required, because the download is processed by aria2. Also new downloads created by extension (sent to aria2 RPC) have no download ids.

Technically, I can't do the same job
![downloads show usage](https://user-images.githubusercontent.com/8744936/148648341-3906b7fc-8730-48ed-9f27-428792b50678.png)

**Comment by g-eipi10** [comment]
Yeah, I also checked the code of `Download Manager (S3)` yesterday, and usually those extensions utilize browser's built-in download to open downloaded file via the ID. If the built-in download is canceled (to use aria2's download), it can't open that folder.
