### ISSUE TITLE
Some downloads are not captured

### ISSUE THREAD

**Issue by SelfishSailfish** [jc3213/download_with_aria2#56]
If I try to download a pdf file using "Save As"  option in the dropdown, the built-in firefox is used instead of this aria2.
Is this a bug or a feature?

**Comment by jc3213** [comment]
If you are using Firefox, you can try to trun `Capture Web Request` on. That's because Firefox fires `downloads.onCreated` Event when download has already been started. 

If the file is very small or your network is fast enough. The download is already been finished by the browser, before it can be cancelled and take over by the extension.
